### PR TITLE
Event delegation - Options Object - Render with no observers - Static VTree option

### LINKED ISSUE #55: not rendering when sources are not subscribed to
# Overview
When the sources are not subscribed to nothing will be rendered.

Minimal code to reproduce
```js
const main= () => ({
  DOM: most.just(div())
})

run(main, {DOM: makeDOMDriver('.selector')}
```

All the tests continue to pass because in some shape or form, they subscribe to sources.
```js
const {sources} = run(main, drivers)

sources.DOM.select(':root').observable.observe() // 
```

### LINKED ISSUE #57: Options object from makeDOMDriver()
Currently `makeDOMDriver()` accepts a `container` and an array of snabbdom modules to load.
```js
makeDOMDriver('.selector', [
  require('snabbdom/modules/props'),
  require('snabbdom/modules/style')
])
```

I'd like to make the second parameter an optional object. i.e.
```js
makeDOMDriver('.selector', {
  modules: [
    require('snabbdom/modules/props'),
    require('snabbdom/modules/style')
  ]
})
```
in order to gain flexibility in the future without the needing to further break the API. We are pre-1.0 now, and I would think it better now than later.

### LINKED ISSUE #58: Add option for a static vTree.
The is a small part of my reasoning for  #57 

# Overview

If we decided to accept #57, I would like to add an option for a static vTree
By a static vTree, I mean a vTree which does not have any nested streams. This can avoid the need for transposition for further performance enhancements in such scenarios that the view is powered by other sources like a database. vTreeParser() is by far one of the most expensive functions in this library, because of all of the recursion, and most.combine() is one of the costlier operators most has.

# Potential API

```
makeDOMDriver('.selector', {staticVTree: true})
```

# Possible solution
[this line](https://github.com/motorcyclejs/dom/blob/develop/src/makeDOMDriver.js#L60) would become 
```js
.map(vTree => vTreeParser(vTree, staticVTree))
```
And [here](https://github.com/motorcyclejs/dom/blob/develop/src/vTreeParser.js#L16-L17) would become
```js
(vTree, staticVTree) => {
  if (staticVTree) {
    return most.just(vTree)
  } else if (!vTree) {
```

### LINKED ISSUE #59: Better empty array handling in fromEvent
# Overview

Add a better, more expected, outcome when select() returns an empty array to events()

# Motivation
Currently fromEvent will throw and erorr when there is an empty array.

# Solution

Return `most.empty()` instead to keep the application running properly.

### PR DESCRIPTION
**Pull request by TylorS**
I totally know this is frowned upon, but this closes 3 issues. Moving to event delegation was a very large undertaking, and renders the other PR's next to impossible to merge easliy.

So,

1. Event Delegation - Moves from snabbdom-selector and matching against the VTree to attaching event listeners to the root Element and filtering for the proper targets. See cyclejs/cycle-dom#85 for more discussion.

2. Options Object - Supersedes #61 

3. Render with no observers - Supersedes #56 

4. Static VTree option - Solution for #58 

Closes #55
Closes #57
Closes #58
Closes #59 - Renders this unneeded.

References #4

### CODE REVIEW

File: src/events.js [hunk 1]
```diff
@@ -1,22 +1,50 @@
...
     }
+    return element$
+      .map(element => {
+        return {element, selector}
+      })
+      .skipRepeatsWith((prev, curr) => {
+        return prev.selector.join(``) === curr.selector.join(``)
+      })
+      .map(({element}) => element)
+      .map(elements => {
```
Comment (staltz) [inline src/events.js]: @TylorS since Motorcycle is about performance, I think you can join these two maps here, it's unnecessary overhead.

Comment (TylorS) [inline src/events.js]: Nice catch! :+1:
